version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
